name: sleek_circular_slider
description: A highly customizable circular slider/progress bar & spinner for Flutter.
version: 2.0.1
homepage: https://github.com/matthewfx/sleek-circular-slider

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
